name: Node CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-and-dedupe:
    runs-on: ubuntu-latest

    name: Lint & Deduplicate deps on node 10.x and ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint codebase
        run: yarn lint:post-build

      - name: Deduplicate dependencies
        run: yarn deduplicate:check

  test:
    name: Test on Node ${{ matrix.node }} and ${{ matrix.os }} using ${{ matrix.package_manager }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['10.x', '12.x', '14.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]
        package_manager: [npm, yarn2]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Restore yarn2 cache
        if: ${{ matrix.package_manager == 'yarn2' }}
        uses: actions/cache@v2
        with:
          path: |
            test/yarn2/.yarn/cache
            test/yarn2/yarn.lock
          key: ''

      - name: Prepare yarn2 cache and seed lockfile
        if: ${{ matrix.package_manager == 'yarn2' }}
        run: cd test/yarn2 && touch yarn.lock && yarn
        env:
          TSDX_TEST_PACKAGE_MANAGER: ${{ matrix.package_manager }}

      - name: Test package
        run: yarn test:post-build
        env:
          TSDX_TEST_PACKAGE_MANAGER: ${{ matrix.package_manager }}
